name: CI/CD

on:
  push:
  pull_request:

env:
  PROJECT_NAME: dc-golang
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
  DOCKER_TAG: ${{ github.sha }}
  GO_VERSION: ^1.21.4

jobs:
  deploy-test:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/prod'
    concurrency: deploy-test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}

          X_BASE_URI: https://mobility.share.opendatahub.testingmachine.eu/json
          X_OAUTH_AUTH_URI: https://auth.opendatahub.testingmachine.eu/auth
          X_OAUTH_TOKEN_URI: https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token
          X_OAUTH_CLIENT_ID: odh-mobility-datacollector-development
          X_OAUTH_CLIENT_NAME: odh-mobility-datacollector-development
          X_OAUTH_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_TEST }}
          X_OAUTH_CLIENT_SCOPE: openid
          
          X_PROVENANCE_VERSION: 0.0.0
          X_PROVENANCE_NAME: dc-golang-helloword
          
          X_LOG_LEVEL: INFO

          X_SCHEDULER_CRON: "0 */10 * * * *"

      - name: Build go application
        run: go build -o main
        working-directory: src

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy application
        uses: noi-techpark/github-actions/docker-deploy@v2
        with:
          hosts: 'test'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-username: 'noi-techpark-bot'
          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project-name: ${{ env.PROJECT_NAME }}